defmodule Abyssalwatch.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :username, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:modules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :external_id, :text, null: false
      add :name, :text, null: false
      add :type_id, :bigint, null: false
      add :type_name, :text
      add :attributes, :map, default: %{}
      add :price, :decimal, default: "0"
      add :score, :float, default: 0.0
      add :source, :text, default: "mutamarket"
      add :available, :boolean, default: true
      add :contract_id, :text
      add :seller_name, :text
      add :location, :text
      add :last_seen, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:modules, [:external_id], name: "modules_unique_external_id_index")

    create table(:module_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :eve_type_id, :bigint, null: false
      add :name, :text, null: false
      add :category, :text, null: false
      add :slot_type, :text, null: false
      add :base_attributes, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:module_types, [:eve_type_id],
             name: "module_types_unique_eve_type_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:module_types, [:eve_type_id],
                     name: "module_types_unique_eve_type_id_index"
                   )

    drop table(:module_types)

    drop_if_exists unique_index(:modules, [:external_id],
                     name: "modules_unique_external_id_index"
                   )

    drop table(:modules)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
