defmodule Abyssalwatch.Repo.Migrations.WatchlistsPhase2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:watchlists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :module_type_id, :bigint, null: false
      add :module_type_name, :text
      add :important_attributes, :map, default: %{}
      add :unimportant_attributes, :map, default: %{}
      add :price_threshold, :decimal
      add :min_score, :float
      add :notifications_enabled, :boolean, default: true
      add :last_checked_at, :utc_datetime_usec
      add :match_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "watchlists_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:watchlists, [:user_id, :name],
             name: "watchlists_unique_user_watchlist_name_index"
           )

    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :module_external_id, :text, null: false
      add :module_name, :text
      add :module_price, :decimal
      add :module_score, :float
      add :module_attributes, :map, default: %{}
      add :read, :boolean, default: false
      add :sent_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :watchlist_id,
          references(:watchlists,
            column: :id,
            name: "notifications_watchlist_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:notifications, [:watchlist_id, :module_external_id],
             name: "notifications_unique_recent_notification_index"
           )
  end

  def down do
    drop_if_exists unique_index(:notifications, [:watchlist_id, :module_external_id],
                     name: "notifications_unique_recent_notification_index"
                   )

    drop constraint(:notifications, "notifications_user_id_fkey")

    drop constraint(:notifications, "notifications_watchlist_id_fkey")

    drop table(:notifications)

    drop_if_exists unique_index(:watchlists, [:user_id, :name],
                     name: "watchlists_unique_user_watchlist_name_index"
                   )

    drop constraint(:watchlists, "watchlists_user_id_fkey")

    drop table(:watchlists)
  end
end
